version: "3.3"
services:
  fullnode:
    image: mysten/sui-node:stable
    ports:
    - "9000:9000"
    - "9184:9184"
    expose:
    - "9000"
    - "9184"
    volumes:
    - /var/sui/fullnode.yaml:/sui/fullnode.yaml:ro
    - /var/sui/genesis.blob:/var/sui/genesis.blob:ro
    - /root/sui/db:/var/sui/db:rw
    command: ["/usr/local/bin/sui-node", "--config-path", "fullnode.yaml"]
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.8"
          memory: 7168M

